name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - SonarCloud 
    
    - name: Build the Docker image
      run: docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:v1 .

    - name: Check for Images
      run: docker images 
