name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - SonarCloud 
    
    - name: Build the Docker image
      run: docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:v1 .

    - name: Check for Images
      run: docker images 

    - name: Run Trivy Image Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:v1
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
      
